services:
  backend:
    build:
      context: .docker/nestjs
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./projects/backend:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=${BACKEND_NODE_ENV}
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=mysql://root:${DATABASE_MYSQL_ROOT_PASSWORD}@database:${DATABASE_MYSQL_PORT}/${DATABASE_MYSQL_DATABASE}
      # - DATABASE_URL=mysql://${DATABASE_MYSQL_USER}:${DATABASE_MYSQL_PASSWORD}@database:${DATABASE_MYSQL_PORT}/${DATABASE_MYSQL_DATABASE}
    depends_on:
      - database
    networks:
      - pay-network
    command: sh -c "npm install && npx prisma migrate dev && npm run start:dev"

  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_MYSQL_DATABASE}
      - MYSQL_USER=${DATABASE_MYSQL_USER}
      - MYSQL_PASSWORD=${DATABASE_MYSQL_PASSWORD}
    ports:
      - ${DATABASE_MYSQL_PORT}:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    restart: always
    networks:
      - pay-network

  frontend:
    image: nginx:latest
    working_dir: /usr/share/nginx/html
    ports:
      - ${FRONTEND_PORT}:80
    volumes:
      - ./projects/frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - pay-network

networks:
  pay-network:
    name: pay-network
