@baseUrl = http://localhost:3000/customers

### Create a new customer
# @name createCustomer
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Andreia Antônia Bernardes",
  "cpfCnpj": "44581048028",
  "email": "andreia.antonia.bernardes@localhost.com"
}

### Get customer by cpfCnpj
# @name getCustomer
GET {{baseUrl}}/{{createCustomer.response.body.cpfCnpj}}

