@baseUrl = http://localhost:3000/payments

@customerId = 55128752-bb46-4247-b608-248f0150c521

### Create Payment
# @name createPaymentBill
POST {{baseUrl}}
Content-Type: application/json

{
    "customerId": "{{customerId}}",
    "billingType": "BILL",
    "value": 100,
    "dueDate": "2025-02-28"
}

### Create Payment with Credit Card
# @name createPaymentCreditCard
POST {{baseUrl}}
Content-Type: application/json

{
    "customerId": "{{customerId}}",
    "billingType": "CREDIT_CARD",
    "value": 101,
    "dueDate": "2025-02-28",
    "creditCard": {
        "number": "5325423243572683",
        "holderName": "John Doe",
        "expirationMonth": 11,
        "expirationYear": 2026,
        "ccv": "217"
    }   
}

### Create Payment with PIX
# @name createPaymentPix
POST {{baseUrl}}
Content-Type: application/json

{
    "customerId": "{{customerId}}",
    "billingType": "PIX",
    "value": 102,
    "dueDate": "2025-02-28"
}

### Bill Payment
@paymentId = {{createPaymentBill.response.body.id}}
@billingType = {{createPaymentBill.request.body.billingType}}
@value = {{createPaymentBill.request.body.value}}
@netValue = {{createPaymentBill.response.body.gatewayResponse.netValue}}

### Credit Card Payment
# @paymentId = {{createPaymentCreditCard.response.body.id}}
# @billingType = {{createPaymentCreditCard.request.body.billingType}}
# @value = {{createPaymentCreditCard.request.body.value}}
# @netValue = {{createPaymentCreditCard.response.body.gatewayResponse.netValue}}

### PIX Payment
# @paymentId = {{createPaymentPix.response.body.id}}
# @billingType = {{createPaymentPix.request.body.billingType}}
# @value = {{createPaymentPix.request.body.value}}
# @netValue = {{createPaymentPix.response.body.gatewayResponse.netValue}}

### Get Payment by ID
# @name getPaymentById
GET {{baseUrl}}/{{paymentId}}

@externalId = {{getPaymentById.response.body.externalId}}
@externalCustomerId = {{getPaymentById.response.body.gatewayResponse.customer}}
### Handle Webhook
POST {{baseUrl}}/webhook
Content-Type: application/json

{
    "event": "PAYMENT_RECEIVED",
    "payment": {
        "id": "{{externalId}}",
        "customer": "{{externalCustomerId}}",
        "value": {{value}},
        "netValue": "{{netValue}}",
        "billingType": "{{billingType}}",
        "status": "RECEIVED",
        "dueDate": "2025-02-28",
        "paymentDate": "2025-02-14"
    }
}
